### ISSUE TITLE
图全挂了

### ISSUE THREAD

**Issue by Johnmc104** [WalkerLau/DetectHumanFaces#1]
rt

**Comment by WalkerLau** [comment]
> rt

我这边还有不同地方的几个小伙伴都是能正常访问看得到图的。这可能与你的网络有关，我之前也试过加载不出GitHub的图，你可以百度一下解决方法。

**Comment by Johnmc104** [comment]
> > rt
> 
> 我这边还有不同地方的几个小伙伴都是能正常访问看得到图的。这可能与你的网络有关，我之前也试过加载不出GitHub的图，你可以百度一下解决方法。

好的
